myMD::Model::DataModel::DoctorsLetter
Doctor myMD.Model.DataModel.DoctorsLetter.DatabaseDoctor
Der Doktor, der diesen Arztbrief erstellt hat und dem der Arztbrief eindeutig zugeordnet werden kann. Ein Doktor kann dabei mehrere Arztbriefe erstellt haben. Wird automatisch beim Lesen aus der Datenbank gesetzt.
Referenced by myMD.Model.DataModel.DoctorsLetter.Equals, myMD.Model.ParserModel.FileToDatabaseParser.ParseFile.
List<DoctorsLetterGroup> myMD.Model.DataModel.DoctorsLetter.DatabaseGroups
Die Arztgruppen in denen dieser Arztbrief enthalten ist. Eine Arztbriefgruppe enthält dabei mehrere Arztbriefe. Wird automatisch beim Lesen aus der Datenbank gesetzt.
List<Medication> myMD.Model.DataModel.DoctorsLetter.DatabaseMedication
Die Medikationen die in diesem Arztbrief verordnet wurde Einer Medikation kann dabei eindeutig ein Arztbrief zugeordnet werden. Wird automatisch beim Lesen aus der Datenbank gesetzt.
Referenced by myMD.Model.DataModel.DoctorsLetter.Equals.
string myMD.Model.DataModel.DoctorsLetter.Diagnosis
myMD.ModelInterface.DataModelInterface.IDoctorsLetter::Diagnosis()
Referenced by myMD.Model.DataModel.DoctorsLetter.Equals.
int myMD.Model.DataModel.DoctorsLetter.DoctorID
Fremdschlüssel zum Doktor dieses Arztbriefs für die Datenbank.
string myMD.Model.DataModel.DoctorsLetter.Filepath
Jede Instanz dieser Klasse basiert auf einer Datei. Dies ist der Pfad zu dieser Datei. Sollte bei der Erstellung aus der Datei gesetzt werden.
Referenced by myMD.Model.DataModel.DoctorsLetter.Equals.
IList<IDoctorsLetterGroup> myMD.Model.DataModel.DoctorsLetter.Groups
myMD.ModelInterface.DataModelInterface.IDoctorsLetter::Groups()
IList<IMedication> myMD.Model.DataModel.DoctorsLetter.Medication
myMD.ModelInterface.DataModelInterface.IDoctorsLetter::Medication()
IDoctor myMD.Model.DataModel.DoctorsLetter.Doctor
myMD.ModelInterface.DataModelInterface.IDoctorsLetter::Doctor()
myMD.Model.DataModel.DoctorsLetter.DoctorsLetter()
Initialisiert nötige Listen.
void myMD.Model.DataModel.DoctorsLetter.AddToGroup(DoctorsLetterGroup group)
Überladung für konkrete Arztbriefgruppen.
myMD.Model.DataModel.DoctorsLetter::AddToGroup(ModelInterface.DataModelInterface.IDoctorsLetterGroup)
References myMD.Model.DataModel.DoctorsLetterGroup.Add.
Referenced by myMD.Model.DataModel.DoctorsLetterGroup.Add.
void myMD.Model.DataModel.DoctorsLetter.AddToGroup(IDoctorsLetterGroup group)
myMD.ModelInterface.DataModelInterface.IDoctorsLetter::AddToGroup(ModelInterface.DataModelInterface.IDoctorsLetterGroup)
void myMD.Model.DataModel.DoctorsLetter.AttachMedication(Medication med)
Überladung für konkrete Medikationen.
myMD.Model.DataModel.DoctorsLetter::AttachMedication(ModelInterface.DataModelInterface.IMedication)
References myMD.Model.DataModel.Medication.AttachToLetter.
Referenced by myMD.Model.DataModel.Medication.AttachToLetter.
void myMD.Model.DataModel.DoctorsLetter.AttachMedication(IMedication med)
myMD.ModelInterface.DataModelInterface.IDoctorsLetter::AttachMedication(ModelInterface.DataModelInterface.IMedication)
override void myMD.Model.DataModel.DoctorsLetter.Delete()
Löst alle der Klasse bekannten Assoziatonen auf und löscht die Datei aus der dieser Arztbrief stammt.
myMD.Model.DataModel.Entity::Delete()
void myMD.Model.DataModel.DoctorsLetter.DisattachMedication(Medication med)
Überladung für konkrete Medikationen.
myMD.Model.DataModel.DoctorsLetter::DisattachMedication(ModelInterface.DataModelInterface.IMedication)
References myMD.Model.DataModel.Medication.DisattachFromLetter.
Referenced by myMD.Model.DataModel.Medication.DisattachFromLetter.
bool myMD.Model.DataModel.DoctorsLetter.Equals(DoctorsLetter other)
Zwei Arztbriefe sind genau dann gleich, wenn sie als Daten gleich sind, ihr Dateipfad, ihr Doktor, ihre Diagnose und ihre Medikationen gleich sind.
System.IEquatable<T>::Equals(T)
References myMD.Model.DataModel.DoctorsLetter.Filepath, myMD.Model.DataModel.DoctorsLetter.Diagnosis, myMD.Model.DataModel.DoctorsLetter.DatabaseMedication, myMD.Model.DataModel.DoctorsLetter.DatabaseDoctor.
override bool myMD.Model.DataModel.DoctorsLetter.Equals(Object obj)
System.Object::Equals(System.Object)
override int myMD.Model.DataModel.DoctorsLetter.GetHashCode()
System.Object::GetHashCode()
void myMD.Model.DataModel.DoctorsLetter.RemoveFromGroup(DoctorsLetterGroup group)
Überladung für konkrete Arztbriefgruppen.
myMD.Model.DataModel.DoctorsLetter::RemoveFromGroup(ModelInterface.DataModelInterface.IDoctorsLetterGroup)
References myMD.Model.DataModel.DoctorsLetterGroup.Remove.
Referenced by myMD.Model.DataModel.DoctorsLetterGroup.Remove.
void myMD.Model.DataModel.DoctorsLetter.RemoveFromGroup(IDoctorsLetterGroup group)
myMD.ModelInterface.DataModelInterface.IDoctorsLetter::RemoveFromGroup(Model.DataModelInterface.IDoctorsLetterGroup)
void myMD.Model.DataModel.DoctorsLetter.DisattachMedication(IMedication med)
myMD.ModelInterface.DataModelInterface.IDoctorsLetter::RemoveMedication(Model.DataModelInterface.IMedication)
DoctorsLetter myMD.Model.DataModel.DoctorsLetter.ToDoctorsLetter()
Da diese Klasse bereits den verlangten Rückgabetyp hab, ist keine Konvertierung nötig.
myMD.ModelInterface.DataModelInterface.IDoctorsLetter::ToDoctorsLetter()