myMD::Model::FileHelper::IFileHelper
string myMD.Model.FileHelper.IFileHelper.GetLocalFilePath(string filename)
Erstellt die gegebene Datei im lokalen Dateisystem, falls sie noch nicht existiert
filename Dateipfad im lokalen Dateisystem Der vollständige Dateipfad
Referenced by myMD.Model.DatabaseModel.EntityDatabase.EntityDatabase, myMD.Model.ParserModel.Hl7ToDatabaseParser.Init.
string myMD.Model.FileHelper.IFileHelper.WriteLocalFileFromString(string format, string data)
Erstellt eine neue Datei mit eindeutigem Namen und dem gegebenen Format aus dem gegebenen Byte Array.
format Format der Datei data Daten der Datei Der vollständige Dateipfad
Referenced by myMD.Model.ModelFacade.ModelFacade.GetFilesFromServer.
void myMD.Model.FileHelper.IFileHelper.DeleteFile(string filename)
Löscht die gegebene Datei im lokalen Dateisystem
filename Die zu löschende Datei