myMD::Model::DatabaseModel::IEntityDatabase
void myMD.Model.DatabaseModel.IEntityDatabase.Activate(IProfile profile)
Aktiviert ein Profil.
profile Das zu aktivierende Profil
void myMD.Model.DatabaseModel.IEntityDatabase.Delete(IEntity entity)
Löscht eine Entität aus der Datenbank.
entity Die zu löschende Entität
IProfile myMD.Model.DatabaseModel.IEntityDatabase.GetActiveProfile()
Gibt das aktive Profile zurück.
Das zurzeit aktive Profil
IList<IDoctorsLetterGroup> myMD.Model.DatabaseModel.IEntityDatabase.GetAllDoctorsLetterGroups()
Holt alle Arztbriefgruppen des zur Zeit aktiven Profils aus der Datenbank.
Liste aller Arztbriefgruppen des aktiven Profils
IList<IDoctorsLetter> myMD.Model.DatabaseModel.IEntityDatabase.GetAllDoctorsLetters()
Holt alle Arztbriefe des zur Zeit aktiven Profils aus der Datenbank.
Liste aller Arztbriefe des aktiven Profils
IList<IMedication> myMD.Model.DatabaseModel.IEntityDatabase.GetAllMedications()
Holt alle Medikationen des zur Zeit aktiven Profils aus der Datenbank.
Liste aller Medikationen des aktiven Profils
IList<IProfile> myMD.Model.DatabaseModel.IEntityDatabase.GetAllProfiles()
Holt alle Profile aus der Datenbank.
Liste aller in der Datenbank gespeicherten Profile
Referenced by myMD.Model.ModelFacade.ModelFacade.ModelFacade.
IDoctor myMD.Model.DatabaseModel.IEntityDatabase.GetDoctor(IDoctor doctor)
Suche nach ähnlichem Arzt in der Datenbank.
doctor Suche nach Arzt der ähnlich zu diesem Arzt ist Ähnlicher Arzt aus der Datenbank oder null falls kein solcher Arzt existiert
Referenced by myMD.Model.ParserModel.FileToDatabaseParser.ParseFile.
IProfile myMD.Model.DatabaseModel.IEntityDatabase.GetProfile(IProfile profile)
Suche nach ähnlichem Profil in der Datenbank.
profile Suche nach Profil das ähnlich zu diesem Profil ist Ähnliches Profil aus der Datenbank oder null falls kein solches Profil existiert
Referenced by myMD.Model.ParserModel.FileToDatabaseParser.ParseFile.
void myMD.Model.DatabaseModel.IEntityDatabase.Insert(IEntity entity)
Fügt eine Entität in die Datenbank zu dem zur Zeit aktiven Profil ein.
entity Die einzufügende Entität
Referenced by myMD.Model.ModelFacade.ModelFacade.CreateEmptyGroup, myMD.Model.ModelFacade.ModelFacade.CreateEmptyMedication, myMD.Model.ModelFacade.ModelFacade.CreateEmptyProfile, myMD.Model.ParserModel.FileToDatabaseParser.ParseFile.
void myMD.Model.DatabaseModel.IEntityDatabase.Update(IEntity entity)
Aktualisiert eine Entität in der Datenbank.
entity Die zu aktualisierende Entität