myMD::Model::EntityFactory::IEntityFactory
IMedication myMD.Model.EntityFactory.IEntityFactory.CreateEmptyMedication()
Erstellt eine neue, leere Medikation.
Die neue Medikation
Referenced by myMD.Model.ModelFacade.ModelFacade.CreateEmptyMedication.
IDoctorsLetterGroup myMD.Model.EntityFactory.IEntityFactory.CreateEmptyGroup()
Erstellt eine neue, leere Arztbriefgruppe.
Die neue Arztbriefgruppe
Referenced by myMD.Model.ModelFacade.ModelFacade.CreateEmptyGroup.
IProfile myMD.Model.EntityFactory.IEntityFactory.CreateEmptyProfile()
Erstellt ein neues, leeres Profil.
Das neue Profil
Referenced by myMD.Model.ModelFacade.ModelFacade.CreateEmptyProfile.
IDoctorsLetter myMD.Model.EntityFactory.IEntityFactory.CreateEmptyDoctorsLetter()
Erstellt einen neuen, leeren Arztbrief.
Der neue Arztbrief